### ISSUE TITLE
Dogecoin Core 1.14.6 on a Raspberry Pi Automated Install - Pi 2 Model B V1.1 (hardware specific)

### ISSUE THREAD

**Issue by tosufever** [veryengineer/collab#15]
dude. this installer is already much wow & that was fing fast!

here's what i did. i probably need help understanding what (relevant) and where, to parse this in [engineer]   :-)

scenario:
*user hasn't loaded a pi in 2+ years
Pi 2 Model B V1.1, 1gb
128gb sd
raspberry pi image flasher for windows https://www.raspberrypi.com/software/
os version? "raspberry Pi OS (32-bit)" Bullseye 2022-09-22 - latest 32bit
flashed image, ran script, working webui, running core.

current status:
still waiting for initial sync? 
+1hr booted. stop services, reboot. working webui. working start button. webui status changes after start. dogecoind running. to an untrained eyeball, tail webui log looks like it's talking blockchain. webui sync status: todays date. webui connected peer list: full. i think i'm stuck in the wait 5 minutes phase? screenshot:

![workingwebui](https://user-images.githubusercontent.com/108495285/219551589-1c881f31-3475-4483-8614-046cd6dbee8b.PNG)

there was some red floating by during install:

![error during install](https://user-images.githubusercontent.com/108495285/219552446-eb7cadfd-d151-41a5-b8f9-ad957071bc33.PNG)

however the script completed without issue: 

![error during install4](https://user-images.githubusercontent.com/108495285/219552541-518b09ac-21f2-46a7-9292-f0b6183c02e7.PNG)

basic network environment. standard firewall/dhcp (external 22556 not open, yet) - everything else network, works. direct resolve of ip from physical gui:

![error during install3](https://user-images.githubusercontent.com/108495285/219553880-11adece2-e526-4552-a9c4-8075e0763e22.PNG)

other notes:
- i kind of hate this github edit interface. protips & tools appreciated (etiquette?) [collab the regular shibes] 
- i edited the sbc table. hopefully it's not broken :) 
- the sd card slot on this raspberry pi was broken. of course. the card eject & latch mechanism was hard set to eject. protip: carefully brute force the eject mechanism with snips. sd probably needs hotglued in place
- first try - i didn't rtfm (reflash). 
- second run, i rtfm. observation: it might could get confusing for some shibes who ((now)specifically) follow all the steps in the destructions. suggestion: edit to parse armbian & raspbian separately? 
- also second run... from empty flash to running dogecoind... it doesn't take but a few minutes to be up and running. it was simple and it was fast! this is the way.
- the webui works great even on mobile. ios/safari can login to the webui console, but it appears to only input commands, no output, refresh console. 
- also ios/mobile infinite scrolls the log... and it starts you at the top. 
- i still need to change the default password (mentioned, but missing from gui? assume future)

bigger picture:
[ ok it works, (maybe) but does the hardware fit?]  idk. probably not? 
- i was honestly surprised there was a modern install image for this old of a pi. my preconceived notion: hardware limitation.
- note* this install might be overclocked from 900mhz to 1ghz? setting may or may not have survived initial rtfm. running no heatsink 
-  clean install with gui & updates... this thing is (deceptively?) fast/snappy. the webui feels instantly responsive. all with the gui running on a monitor in the background. (rtfm2 must have defaulted rpi downloader to gui) i swear.  :) 
- it's notably usably faster than i thought it would be? 

other other:
- i vaguely remember some fundamental hardware change (between the pi2a and pi3b?) that impacted a ton of packages... some kind of change with the pi2b2? pi2b2. pi2b2! - anyway if you have to write something different for the pi2, or it takes separate lts maintenance work... maybe leave this one out of the running. (surprisingly it does seem like it'll work at the most basic level just fine) 
- do we need to drill down on the raspberry pi4 models, or can they all (for our purposes) again be covered under this same installer script / single image? 

the end.

**Comment by DogestMaximus** [comment]
- Separating the instructions would be better I def agree- it's a mind-bender.

- Did you rpikernelhack?  Could be an issue with the mirror- I see UFW didn't install and exfat-utils was part of the Raspian dist only.
Packages shouldn't have been different unless you grabbed a different distribution which would make it likely- the Pi 2 and 3 are a little different and the Pi 1 I built from source so no webserver on that guy.

- Initial block download will probably take awhile you can check it from the CLI in /dogecoin/bin/ with ./dogecoin-cli getinfo or ./dogecoin-cli getblockchaininfo.  If it takes too long you can do what I did and copy the .dogecoin (hidden data directory) over just delete the wallet.dat file first.  Starting dogecoind or dogecoin-cli -daemon should generate a new one automatically- I think... @patricklodder would know for certain; definitely don't want multiple copies of the same wallet.dat on different nodes though I can imagine that will probably mess with tx's.


_"i kind of hate this github edit interface. protips & tools appreciated (etiquette?) [collab the regular shibes]"_   -it's markdown; but [here's a cheatsheet](https://gist.github.com/jonschlinkert/5854601#italics) 

_" [ ok it works, (maybe) but does the hardware fit?] idk. probably not?"_  -sure it's fine...  what else were you planning on using it for? xD

Glad you got it working.  Very nice work.

If it becomes too much of a waiting game or fails on you this Arch build I'm completing may be the answer for some of the retro application's reliability.  They can always be pruned as well. ;)

**Comment by tosufever** [comment]
did i rpikernelhack? not specifically? i went straight from imaging a new clean 32bit image (latest via raspberry pi oem image downloader utility) to running your script. no other config changes (what got me into trouble the first time)

i'll run getblockchain info later & post. i just checked the webui & it looks like core is restarting on it's own. see message here:

![image](https://user-images.githubusercontent.com/108495285/219810896-fe30ddc7-4f56-44b6-a808-fac86943c369.png)

**Comment by tosufever** [comment]
it's still not sync'd. so far it looks like it's written about 64gb to disk. it does look like it's still going? here's the output of getblockchaininfo:

<img width="513" alt="blockchaininfo" src="https://user-images.githubusercontent.com/108495285/220209030-6fe95887-7783-4487-9576-d2c548c6ef87.PNG">

and getinfo:

<img width="435" alt="getinfo" src="https://user-images.githubusercontent.com/108495285/220209465-3162b5d5-a088-401e-9214-b729cc5b9ef5.PNG">

i'll keep waiting :)

**Comment by tosufever** [comment]
lol... i might have found why it's taking so long. and only because i was lazy. "low voltage warning please check your power supply" :-)

**Comment by tosufever** [comment]
it looks like it finally finished sync. 
*note - it also turns out what ever image i used, had significant updates. looks like it also all survived an os version upgrade post install :-) 
Pro tip: not all old power adapters are created equal. 
<img width="990" alt="sync" src="https://user-images.githubusercontent.com/108495285/221085319-8b912dd2-76e3-4fd5-934d-97240f2aa7f2.PNG">

**Comment by DogestMaximus** [comment]
>  Pro tip: not all old power adapters are created equal.

This is for sure!
