### ISSUE TITLE
location for worthy reference links

### ISSUE THREAD

**Issue by tosufever** [veryengineer/collab#3]
if the wiki is the place to dump reference links to similar relevant projects, discussions, etc... i'll add stuff as i find it. would be cool if it forces a link and a description(or sub category) as to why it might be useful

**Comment by daank-c** [comment]
I just added something similar in the discussions, but more as "possibly relevant tools".

Also, if y'all had a resource dump location, some of us less technically-minded folks could come in and reorganise them in a way that's more accessible and descriptive. This might leave you folks more available to search for more relevant resources.

**Comment by tosufever** [comment]
done. any worthy reference links i find, shall appear in the wiki
