### ISSUE TITLE
diagrams and drawings?

### ISSUE THREAD

**Issue by tosufever** [veryengineer/collab#4]
what's the 'visio' like tool of today to share/edit doodles or wiring diagrams etc...? maybe something like a whiteboard for the hardware folk to collaborate would be cool

**Comment by tosufever** [comment]
i'll have git figured out in a minute... meanwhile, lmk if this should have been a discussion.

**Comment by daank-c** [comment]
I would say yes,  issues are used to signal that you're having an issue with software, docs or something of that nature. For example, atm we have 2 files in the repository, the `README.md` file and the `LICENSE` file.  If you noticed an issue/error in either of those two files you'd submit an issue. If this repo had a stable release of functioning software, users would come here to report bugs, and performance issues.

Also, in this case specifically, Patrick has written in the README file that "submitting an issue" is the best way to signal to him that you'd like to take part in the writing of the wiki.

To answer your question about collaborative diagramming, I wrote about it in the discussions [here].(https://github.com/veryengineer/collab/discussions/2)

**Comment by tosufever** [comment]
found & closed?

**Comment by daank-c** [comment]
ur a natural
